#!/bin/bash
# GStreamer pipeline with dynamic PNG overlay using compositor + multifilesrc
# multifilesrc re-reads the PNG file every frame so overlay updates are picked up
# The PNG is generated by wkhtmltoimage + ImageMagick (chroma-key transparency)

CAMERA_DEVICE=$1
WIDTH=$2
HEIGHT=$3
FRAMERATE=$4
BITRATE=$5
SRT_PORT=$6
PNG_PATH=${7:-"/tmp/graphics-overlay.png"}
OVERLAY_TEXT=${8:-""}
SHOW_TIMESTAMP=${9:-"false"}
FONT_SIZE=${10:-48}

# Overlay re-read rate (how often multifilesrc re-reads the PNG)
OVERLAY_FPS=2

echo "🎨 Starting stream with dynamic PNG graphics overlay..."
echo "Camera: $CAMERA_DEVICE"
echo "Resolution: ${WIDTH}x${HEIGHT}@${FRAMERATE}fps"
echo "SRT Port: $SRT_PORT"
echo "PNG Overlay: $PNG_PATH (re-read at ${OVERLAY_FPS} fps)"
echo "Text Overlay: $OVERLAY_TEXT"
echo "Show Timestamp: $SHOW_TIMESTAMP"

# Pipeline uses compositor to blend camera (bottom) with PNG overlay (top)
# multifilesrc with loop=true re-reads the same PNG file at OVERLAY_FPS rate
# This allows the overlay to update when the PNG file changes on disk
exec gst-launch-1.0 -v \
  compositor name=mix \
    sink_0::zorder=0 sink_0::alpha=1.0 \
    sink_1::zorder=1 sink_1::alpha=1.0 \
  ! videoconvert \
  $(if [ -n "$OVERLAY_TEXT" ]; then echo "! textoverlay text=\"$OVERLAY_TEXT\" valignment=bottom halignment=left font-desc=\"Sans Bold $FONT_SIZE\" color=4294967295 xpad=20 ypad=20 shaded-background=true"; fi) \
  $(if [ "$SHOW_TIMESTAMP" = "true" ]; then echo "! clockoverlay valignment=bottom halignment=right font-desc=\"Sans Bold $FONT_SIZE\" color=4294967295 time-format=\"%Y-%m-%d %H:%M:%S\" xpad=20 ypad=20 shaded-background=true"; fi) \
  ! tee name=t \
  \
  v4l2src device=$CAMERA_DEVICE do-timestamp=true \
  ! image/jpeg,width=$WIDTH,height=$HEIGHT,framerate=$FRAMERATE/1 \
  ! jpegdec \
  ! videoconvert \
  ! video/x-raw,width=$WIDTH,height=$HEIGHT,format=RGBA \
  ! queue max-size-buffers=3 leaky=downstream \
  ! mix.sink_0 \
  \
  multifilesrc location=$PNG_PATH loop=true caps="image/png,framerate=${OVERLAY_FPS}/1" \
  ! pngdec \
  ! videoconvert \
  ! videoscale \
  ! video/x-raw,width=$WIDTH,height=$HEIGHT,format=RGBA \
  ! queue max-size-buffers=2 leaky=downstream \
  ! mix.sink_1 \
  \
  t. ! queue max-size-buffers=2 max-size-time=0 max-size-bytes=0 leaky=downstream ! videoconvert \
  ! 'video/x-raw,format=I420' \
  ! x264enc speed-preset=ultrafast tune=zerolatency bitrate=$((BITRATE/1000)) key-int-max=30 \
  ! 'video/x-h264,stream-format=byte-stream' \
  ! h264parse config-interval=-1 \
  ! queue max-size-buffers=2 max-size-time=0 max-size-bytes=0 leaky=downstream \
  ! mpegtsmux alignment=7 \
  ! srtsink uri="srt://:$SRT_PORT" wait-for-connection=false latency=125 \
  \
  t. ! queue max-size-buffers=10 leaky=downstream \
  ! videoscale \
  ! video/x-raw,width=1280,height=720 \
  ! jpegenc quality=75 \
  ! multipartmux boundary=--jpgboundary \
  ! tcpserversink host=0.0.0.0 port=8555 sync=false recover-policy=keyframe

